build = "mvn"

# don't run eslint... it is for js and will detect false positives 
# in javadoc directories.

disableTools = ["eslint"]

# Ignore warnings not relevant to this specific project:
#
# 1) FindSecBugs identifies our use of ThreadLocalRandom as predictable.
# We make extensive use of this class since local search require randomness.
# Our use of randomness in this library is NOT at all security related,
# and rather, we simply need a fast pseudorandom number generator since
# we need to generate large numbers of random numbers. So ignore
# predictable random warnings. 
#
# 2) FindSecBugs generates a few PATH_TRAVERSAL_IN messages ("reads a file whose 
# location might be specified by user input"). The Chips-n-Salsa library includes
# a few parsers for benchmark instances of a few optimization problems. Those 
# parsers are passed the file to parse, and also include methods for outputting
# randomly generated instances to a file (which also accepts filename as input). 
# It is the responsibility of the application that uses the library to appropriately
# obtain the relevant filenames.
#
# 3) FindSecBugs generates PATH_TRAVERSAL_OUT for the same reason as above,
# and we are ignoring them for the same reason.

ignore = ["PREDICTABLE_RANDOM", "PATH_TRAVERSAL_IN", "PATH_TRAVERSAL_OUT"]

# Ignore results from these directories

ignoreFiles = """
docs/api/jquery/
tests/
*.js
"""
