# don't run eslint... it is for js and will detect false positives 
# in javadoc directories.
disableTools = ["eslint"]

# Ignore results from these directories
ignoreFiles = """
docs/api/jquery/
tests/
"""