name: docs

on:
  push:
    branches: [ development ]
    paths: [ '**.java' ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Clean docs
      run: ant -noinput -buildfile build/builddocs.xml clean

    - name: Build docs with Ant
      run: ant -noinput -buildfile build/builddocs.xml
    
    -name: Commit documentation changes
      run: |
        if [ $(git status | grep -c "*.html" || true) == "0" ]; then
          git checkout .
        else
          git config --global user.name 'Vincent A Cicirello'
          git config --global user.email 'cicirello@users.noreply.github.com'
          git commit -am "Automated API website updates."
        fi

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1.6.0
      with:
        base-url-path: https://chips-n-salsa.cicirello.org/
        path-to-root: docs
    
    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.4.0
      with:
        title: "Automated API website updates."
        body: > 
          Automated changes to the API documentation website.
          Documentation updated via javadoc. Sitemap updated by 
          the [generate-sitemap](https://github.com/cicirello/generate-sitemap) 
          GitHub action.  Automated pull-request generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request) 
          GitHub action.
        commit-message: "Automated API documentation website updates."
        author: Vincent A Cicirello <cicirello@users.noreply.github.com>
        committer: Vincent A Cicirello <cicirello@users.noreply.github.com>
        delete-branch: true
